# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'paquete_de_sedimentos_V04.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(905, 528)
        self.gridLayout = QtGui.QGridLayout(Dialog)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.label_00_titulodelpaquetedelaboratorio = QtGui.QLabel(Dialog)
        self.label_00_titulodelpaquetedelaboratorio.setObjectName(_fromUtf8("label_00_titulodelpaquetedelaboratorio"))
        self.verticalLayout_8.addWidget(self.label_00_titulodelpaquetedelaboratorio)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_01_codigo = QtGui.QLabel(Dialog)
        self.label_01_codigo.setObjectName(_fromUtf8("label_01_codigo"))
        self.verticalLayout.addWidget(self.label_01_codigo)
        self.label_02_nderepeticiones = QtGui.QLabel(Dialog)
        self.label_02_nderepeticiones.setObjectName(_fromUtf8("label_02_nderepeticiones"))
        self.verticalLayout.addWidget(self.label_02_nderepeticiones)
        self.label_03_fecha = QtGui.QLabel(Dialog)
        self.label_03_fecha.setObjectName(_fromUtf8("label_03_fecha"))
        self.verticalLayout.addWidget(self.label_03_fecha)
        self.label_04_niveldecota = QtGui.QLabel(Dialog)
        self.label_04_niveldecota.setObjectName(_fromUtf8("label_04_niveldecota"))
        self.verticalLayout.addWidget(self.label_04_niveldecota)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.lineEdit_01_codigo = QtGui.QLineEdit(Dialog)
        self.lineEdit_01_codigo.setObjectName(_fromUtf8("lineEdit_01_codigo"))
        self.verticalLayout_2.addWidget(self.lineEdit_01_codigo)
        self.lineEdit_02_nderepeticiones = QtGui.QLineEdit(Dialog)
        self.lineEdit_02_nderepeticiones.setObjectName(_fromUtf8("lineEdit_02_nderepeticiones"))
        self.verticalLayout_2.addWidget(self.lineEdit_02_nderepeticiones)
        self.lineEdit_03_fecha = QtGui.QLineEdit(Dialog)
        self.lineEdit_03_fecha.setObjectName(_fromUtf8("lineEdit_03_fecha"))
        self.verticalLayout_2.addWidget(self.lineEdit_03_fecha)
        self.lineEdit_04_niveldecota = QtGui.QLineEdit(Dialog)
        self.lineEdit_04_niveldecota.setObjectName(_fromUtf8("lineEdit_04_niveldecota"))
        self.verticalLayout_2.addWidget(self.lineEdit_04_niveldecota)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_05_codigodechapa = QtGui.QLabel(Dialog)
        self.label_05_codigodechapa.setObjectName(_fromUtf8("label_05_codigodechapa"))
        self.verticalLayout_3.addWidget(self.label_05_codigodechapa)
        self.label_06_pesodebotellamasliquido = QtGui.QLabel(Dialog)
        self.label_06_pesodebotellamasliquido.setObjectName(_fromUtf8("label_06_pesodebotellamasliquido"))
        self.verticalLayout_3.addWidget(self.label_06_pesodebotellamasliquido)
        self.label_07_pesodebotella = QtGui.QLabel(Dialog)
        self.label_07_pesodebotella.setObjectName(_fromUtf8("label_07_pesodebotella"))
        self.verticalLayout_3.addWidget(self.label_07_pesodebotella)
        self.label_08_pesodelliquido = QtGui.QLabel(Dialog)
        self.label_08_pesodelliquido.setObjectName(_fromUtf8("label_08_pesodelliquido"))
        self.verticalLayout_3.addWidget(self.label_08_pesodelliquido)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.lineEdit_05_codigodechapa = QtGui.QLineEdit(Dialog)
        self.lineEdit_05_codigodechapa.setObjectName(_fromUtf8("lineEdit_05_codigodechapa"))
        self.verticalLayout_4.addWidget(self.lineEdit_05_codigodechapa)
        self.lineEdit_06_pesodebotellamasliquido = QtGui.QLineEdit(Dialog)
        self.lineEdit_06_pesodebotellamasliquido.setObjectName(_fromUtf8("lineEdit_06_pesodebotellamasliquido"))
        self.verticalLayout_4.addWidget(self.lineEdit_06_pesodebotellamasliquido)
        self.lineEdit_07_pesodebotella = QtGui.QLineEdit(Dialog)
        self.lineEdit_07_pesodebotella.setObjectName(_fromUtf8("lineEdit_07_pesodebotella"))
        self.verticalLayout_4.addWidget(self.lineEdit_07_pesodebotella)
        self.lineEdit_08_pesodelliquido = QtGui.QLineEdit(Dialog)
        self.lineEdit_08_pesodelliquido.setObjectName(_fromUtf8("lineEdit_08_pesodelliquido"))
        self.verticalLayout_4.addWidget(self.lineEdit_08_pesodelliquido)
        self.horizontalLayout_4.addLayout(self.verticalLayout_4)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label_09_pesoinicialdefiltrosfinos = QtGui.QLabel(Dialog)
        self.label_09_pesoinicialdefiltrosfinos.setObjectName(_fromUtf8("label_09_pesoinicialdefiltrosfinos"))
        self.verticalLayout_5.addWidget(self.label_09_pesoinicialdefiltrosfinos)
        self.label_10_pesofinaldefiltrosfinos = QtGui.QLabel(Dialog)
        self.label_10_pesofinaldefiltrosfinos.setObjectName(_fromUtf8("label_10_pesofinaldefiltrosfinos"))
        self.verticalLayout_5.addWidget(self.label_10_pesofinaldefiltrosfinos)
        self.label_11pesoinicialdefiltrosgruesos = QtGui.QLabel(Dialog)
        self.label_11pesoinicialdefiltrosgruesos.setObjectName(_fromUtf8("label_11pesoinicialdefiltrosgruesos"))
        self.verticalLayout_5.addWidget(self.label_11pesoinicialdefiltrosgruesos)
        self.label_12_pesofinaldefiltrosgruesos = QtGui.QLabel(Dialog)
        self.label_12_pesofinaldefiltrosgruesos.setObjectName(_fromUtf8("label_12_pesofinaldefiltrosgruesos"))
        self.verticalLayout_5.addWidget(self.label_12_pesofinaldefiltrosgruesos)
        self.horizontalLayout_5.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.lineEdit_09_pesoinicialdefiltrosfinos = QtGui.QLineEdit(Dialog)
        self.lineEdit_09_pesoinicialdefiltrosfinos.setObjectName(_fromUtf8("lineEdit_09_pesoinicialdefiltrosfinos"))
        self.verticalLayout_6.addWidget(self.lineEdit_09_pesoinicialdefiltrosfinos)
        self.lineEdit_10_pesofinaldefiltrosfinos = QtGui.QLineEdit(Dialog)
        self.lineEdit_10_pesofinaldefiltrosfinos.setObjectName(_fromUtf8("lineEdit_10_pesofinaldefiltrosfinos"))
        self.verticalLayout_6.addWidget(self.lineEdit_10_pesofinaldefiltrosfinos)
        self.lineEdit_11pesoinicialdefiltrosgruesos = QtGui.QLineEdit(Dialog)
        self.lineEdit_11pesoinicialdefiltrosgruesos.setObjectName(_fromUtf8("lineEdit_11pesoinicialdefiltrosgruesos"))
        self.verticalLayout_6.addWidget(self.lineEdit_11pesoinicialdefiltrosgruesos)
        self.lineEdit_12_pesofinaldefiltrosgruesos = QtGui.QLineEdit(Dialog)
        self.lineEdit_12_pesofinaldefiltrosgruesos.setObjectName(_fromUtf8("lineEdit_12_pesofinaldefiltrosgruesos"))
        self.verticalLayout_6.addWidget(self.lineEdit_12_pesofinaldefiltrosgruesos)
        self.horizontalLayout_5.addLayout(self.verticalLayout_6)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_5)
        self.verticalLayout_7.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_13_nombredelaestacion = QtGui.QLabel(Dialog)
        self.label_13_nombredelaestacion.setObjectName(_fromUtf8("label_13_nombredelaestacion"))
        self.horizontalLayout_7.addWidget(self.label_13_nombredelaestacion)
        self.lineEdit_13_nombredelaestacion = QtGui.QLineEdit(Dialog)
        self.lineEdit_13_nombredelaestacion.setObjectName(_fromUtf8("lineEdit_13_nombredelaestacion"))
        self.horizontalLayout_7.addWidget(self.lineEdit_13_nombredelaestacion)
        self.verticalLayout_7.addLayout(self.horizontalLayout_7)
        self.verticalLayout_8.addLayout(self.verticalLayout_7)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pushButton_01anadir = QtGui.QPushButton(Dialog)
        self.pushButton_01anadir.setObjectName(_fromUtf8("pushButton_01anadir"))
        self.horizontalLayout.addWidget(self.pushButton_01anadir)
        self.pushButton_02_editar = QtGui.QPushButton(Dialog)
        self.pushButton_02_editar.setObjectName(_fromUtf8("pushButton_02_editar"))
        self.horizontalLayout.addWidget(self.pushButton_02_editar)
        self.pushButton_03_borrar = QtGui.QPushButton(Dialog)
        self.pushButton_03_borrar.setObjectName(_fromUtf8("pushButton_03_borrar"))
        self.horizontalLayout.addWidget(self.pushButton_03_borrar)
        self.pushButton_04_borrartodo = QtGui.QPushButton(Dialog)
        self.pushButton_04_borrartodo.setObjectName(_fromUtf8("pushButton_04_borrartodo"))
        self.horizontalLayout.addWidget(self.pushButton_04_borrartodo)
        self.verticalLayout_8.addLayout(self.horizontalLayout)
        self.listView_00_basededatoslaboratorio = QtGui.QListView(Dialog)
        self.listView_00_basededatoslaboratorio.setObjectName(_fromUtf8("listView_00_basededatoslaboratorio"))
        self.verticalLayout_8.addWidget(self.listView_00_basededatoslaboratorio)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.pushButton_05_guardar = QtGui.QPushButton(Dialog)
        self.pushButton_05_guardar.setObjectName(_fromUtf8("pushButton_05_guardar"))
        self.horizontalLayout_2.addWidget(self.pushButton_05_guardar)
        self.pushButton_06_guardarcomo = QtGui.QPushButton(Dialog)
        self.pushButton_06_guardarcomo.setObjectName(_fromUtf8("pushButton_06_guardarcomo"))
        self.horizontalLayout_2.addWidget(self.pushButton_06_guardarcomo)
        self.pushButton_07_actualizarbasededatos = QtGui.QPushButton(Dialog)
        self.pushButton_07_actualizarbasededatos.setObjectName(_fromUtf8("pushButton_07_actualizarbasededatos"))
        self.horizontalLayout_2.addWidget(self.pushButton_07_actualizarbasededatos)
        self.pushButton_08_eliminarbasededatos = QtGui.QPushButton(Dialog)
        self.pushButton_08_eliminarbasededatos.setObjectName(_fromUtf8("pushButton_08_eliminarbasededatos"))
        self.horizontalLayout_2.addWidget(self.pushButton_08_eliminarbasededatos)
        self.verticalLayout_8.addLayout(self.horizontalLayout_2)
        self.gridLayout.addLayout(self.verticalLayout_8, 0, 0, 1, 1)
        self.label_01_codigo.raise_()
        self.label_02_nderepeticiones.raise_()
        self.label_03_fecha.raise_()
        self.label_04_niveldecota.raise_()
        self.label_08_pesodelliquido.raise_()
        self.label_05_codigodechapa.raise_()
        self.label_06_pesodebotellamasliquido.raise_()
        self.label_07_pesodebotella.raise_()
        self.label_09_pesoinicialdefiltrosfinos.raise_()
        self.label_10_pesofinaldefiltrosfinos.raise_()
        self.label_11pesoinicialdefiltrosgruesos.raise_()
        self.label_12_pesofinaldefiltrosgruesos.raise_()
        self.label_13_nombredelaestacion.raise_()
        self.label_00_titulodelpaquetedelaboratorio.raise_()
        self.lineEdit_01_codigo.raise_()
        self.lineEdit_02_nderepeticiones.raise_()
        self.lineEdit_03_fecha.raise_()
        self.lineEdit_04_niveldecota.raise_()
        self.lineEdit_07_pesodebotella.raise_()
        self.lineEdit_05_codigodechapa.raise_()
        self.lineEdit_08_pesodelliquido.raise_()
        self.lineEdit_06_pesodebotellamasliquido.raise_()
        self.lineEdit_10_pesofinaldefiltrosfinos.raise_()
        self.lineEdit_11pesoinicialdefiltrosgruesos.raise_()
        self.lineEdit_09_pesoinicialdefiltrosfinos.raise_()
        self.lineEdit_12_pesofinaldefiltrosgruesos.raise_()
        self.lineEdit_13_nombredelaestacion.raise_()
        self.pushButton_01anadir.raise_()
        self.pushButton_02_editar.raise_()
        self.pushButton_03_borrar.raise_()
        self.pushButton_04_borrartodo.raise_()
        self.listView_00_basededatoslaboratorio.raise_()
        self.pushButton_07_actualizarbasededatos.raise_()
        self.pushButton_05_guardar.raise_()
        self.pushButton_06_guardarcomo.raise_()
        self.pushButton_08_eliminarbasededatos.raise_()
        self.label_01_codigo.setBuddy(self.lineEdit_01_codigo)
        self.label_02_nderepeticiones.setBuddy(self.lineEdit_02_nderepeticiones)
        self.label_03_fecha.setBuddy(self.lineEdit_03_fecha)
        self.label_04_niveldecota.setBuddy(self.lineEdit_04_niveldecota)
        self.label_05_codigodechapa.setBuddy(self.lineEdit_05_codigodechapa)
        self.label_06_pesodebotellamasliquido.setBuddy(self.lineEdit_06_pesodebotellamasliquido)
        self.label_07_pesodebotella.setBuddy(self.lineEdit_07_pesodebotella)
        self.label_08_pesodelliquido.setBuddy(self.lineEdit_08_pesodelliquido)
        self.label_09_pesoinicialdefiltrosfinos.setBuddy(self.lineEdit_09_pesoinicialdefiltrosfinos)
        self.label_10_pesofinaldefiltrosfinos.setBuddy(self.lineEdit_10_pesofinaldefiltrosfinos)
        self.label_11pesoinicialdefiltrosgruesos.setBuddy(self.lineEdit_11pesoinicialdefiltrosgruesos)
        self.label_12_pesofinaldefiltrosgruesos.setBuddy(self.lineEdit_12_pesofinaldefiltrosgruesos)
        self.label_13_nombredelaestacion.setBuddy(self.lineEdit_13_nombredelaestacion)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.lineEdit_01_codigo, self.lineEdit_02_nderepeticiones)
        Dialog.setTabOrder(self.lineEdit_02_nderepeticiones, self.lineEdit_03_fecha)
        Dialog.setTabOrder(self.lineEdit_03_fecha, self.lineEdit_04_niveldecota)
        Dialog.setTabOrder(self.lineEdit_04_niveldecota, self.lineEdit_05_codigodechapa)
        Dialog.setTabOrder(self.lineEdit_05_codigodechapa, self.lineEdit_06_pesodebotellamasliquido)
        Dialog.setTabOrder(self.lineEdit_06_pesodebotellamasliquido, self.lineEdit_07_pesodebotella)
        Dialog.setTabOrder(self.lineEdit_07_pesodebotella, self.lineEdit_08_pesodelliquido)
        Dialog.setTabOrder(self.lineEdit_08_pesodelliquido, self.lineEdit_09_pesoinicialdefiltrosfinos)
        Dialog.setTabOrder(self.lineEdit_09_pesoinicialdefiltrosfinos, self.lineEdit_10_pesofinaldefiltrosfinos)
        Dialog.setTabOrder(self.lineEdit_10_pesofinaldefiltrosfinos, self.lineEdit_11pesoinicialdefiltrosgruesos)
        Dialog.setTabOrder(self.lineEdit_11pesoinicialdefiltrosgruesos, self.lineEdit_12_pesofinaldefiltrosgruesos)
        Dialog.setTabOrder(self.lineEdit_12_pesofinaldefiltrosgruesos, self.lineEdit_13_nombredelaestacion)
        Dialog.setTabOrder(self.lineEdit_13_nombredelaestacion, self.pushButton_01anadir)
        Dialog.setTabOrder(self.pushButton_01anadir, self.pushButton_02_editar)
        Dialog.setTabOrder(self.pushButton_02_editar, self.pushButton_03_borrar)
        Dialog.setTabOrder(self.pushButton_03_borrar, self.pushButton_04_borrartodo)
        Dialog.setTabOrder(self.pushButton_04_borrartodo, self.pushButton_05_guardar)
        Dialog.setTabOrder(self.pushButton_05_guardar, self.pushButton_06_guardarcomo)
        Dialog.setTabOrder(self.pushButton_06_guardarcomo, self.pushButton_07_actualizarbasededatos)
        Dialog.setTabOrder(self.pushButton_07_actualizarbasededatos, self.pushButton_08_eliminarbasededatos)
        Dialog.setTabOrder(self.pushButton_08_eliminarbasededatos, self.listView_00_basededatoslaboratorio)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Paquete de sedimentos", None))
        self.label_00_titulodelpaquetedelaboratorio.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">Formulario para Laboratorio de Procesamiento de Muestras</span></p></body></html>", None))
        self.label_01_codigo.setText(_translate("Dialog", "01. Codigo", None))
        self.label_02_nderepeticiones.setText(_translate("Dialog", "02. N° de Repeticiones", None))
        self.label_03_fecha.setText(_translate("Dialog", "03. Fecha", None))
        self.label_04_niveldecota.setText(_translate("Dialog", "04. Nivel de cota", None))
        self.label_05_codigodechapa.setText(_translate("Dialog", "05. Codigo de chapa", None))
        self.label_06_pesodebotellamasliquido.setText(_translate("Dialog", "06. Peso de botella + Liquido", None))
        self.label_07_pesodebotella.setText(_translate("Dialog", "07. Peso de botella", None))
        self.label_08_pesodelliquido.setText(_translate("Dialog", "08. Peso del liquido", None))
        self.label_09_pesoinicialdefiltrosfinos.setText(_translate("Dialog", "09. Peso inicial de filtros finos", None))
        self.label_10_pesofinaldefiltrosfinos.setText(_translate("Dialog", "10. Peso final de filtros finos", None))
        self.label_11pesoinicialdefiltrosgruesos.setText(_translate("Dialog", "11. Peso inicial de filtros gruesos", None))
        self.label_12_pesofinaldefiltrosgruesos.setText(_translate("Dialog", "12. Peso final de filtros gruesos", None))
        self.label_13_nombredelaestacion.setText(_translate("Dialog", "13. Nombre de la estacion", None))
        self.pushButton_01anadir.setText(_translate("Dialog", "&Añadir", None))
        self.pushButton_02_editar.setText(_translate("Dialog", "&Editar", None))
        self.pushButton_03_borrar.setText(_translate("Dialog", "&Borrar", None))
        self.pushButton_04_borrartodo.setText(_translate("Dialog", "Borrar &todo", None))
        self.pushButton_05_guardar.setText(_translate("Dialog", "&Guardar", None))
        self.pushButton_06_guardarcomo.setText(_translate("Dialog", "G&uardar como...", None))
        self.pushButton_07_actualizarbasededatos.setText(_translate("Dialog", "A&ctualiza base de datos", None))
        self.pushButton_08_eliminarbasededatos.setText(_translate("Dialog", "E&liminar base de datos", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Dialog = QtGui.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

